[project]
name = "slashing-allocate"
authors = ["SlashChain Development Team"]
description = "Stake slashing and resource allocation mechanism for blockchain networks"
telemetry = false
requirements = []
[contracts.slashing-allocate]
path = "contracts/slashing-allocate.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
